#ifndef FACTORKEY_APP_CONFIG_H
#define FACTORKEY_APP_CONFIG_H

/*
 *
 * config.h. Generated by cmake from config.h.in
 */

#cmakedefine FACTORKEY_WITH_KWALLET         1
#cmakedefine FACTORKEY_WITH_QT_KEYCHAIN     1
#cmakedefine FACTORKEY_WITH_DUMPING         1
#cmakedefine FACTORKEY_USE_LINUX_PRCTL      1

#endif

